services:  
  api:
    build: ./
    restart: always
    expose: 
      - "5000"
    networks:
      - networkName
    volumes:
      - /api/database:/api/database
    
  frontend:
    build: ./frontend
    restart: always
    expose:
      - "3000"
    depends_on:
      - api
    networks:
      - networkName

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - api
      - frontend
    networks:
      - networkName

networks:
  networkName:
